import React, { useState } from 'react';
import InputText from '../../components/module/inputText';
import Table from '../../components/module/table';
import { BiSearch } from 'react-icons/bi';

const tableVal = {
  tabelHeader: [
    'No',
    'Company',
    'Total',
    'Mothly Topic',
    'Syncing Status',
    'Group Challenge',
    'Individual Challenge',
    'Bonus Activity - Activity Based',
    'Bonus Activity - HLS',
    'Bonus Activity - Content Based : Manual Points 01',
    'Bonus Activity - Content Based : Manual Points 02',
    'Bonus Activity - Content Based : Manual Points 03',
    'Bonus Activity - Content Based : Manual Points 04',
    'Bonus Activity - Content Based : Manual Points 05',
    'Group Challenge Winner: 1st',
    'Group Challenge Winner: 2nd',
    'Group Challenge Winner: 3rd',
    'Group Challenge Leader',
    'Pre-Topic Survery',
    'Post-Topic Survery',
    'Updated On',
  ],
  tableContent: [
    {
      no: 1,
      company: 'BDCC International Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '08 Jan 2022',
    },
    {
      no: 2,
      company: 'Bell Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '08 Jan 2022',
    },
    {
      no: 3,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 4,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 5,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 6,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 7,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 8,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 9,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 10,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 11,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 12,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 13,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 14,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 15,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 16,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 17,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 18,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 19,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 20,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 21,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 22,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 23,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 24,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 25,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 26,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 27,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 28,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 29,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 30,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 31,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 32,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 33,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 34,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 35,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 36,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
    {
      no: 37,
      company: 'BJC Group',
      total: 195,
      monthlyTopic: 10,
      syncingStatus: 10,
      groupChallenge: 50,
      individualChallenge: 20,
      bonusActivityBased: 15,
      bonusActivityHLS: '-',
      bonusActivityContentBased1: 5,
      bonusActivityContentBased2: 5,
      bonusActivityContentBased3: '-',
      bonusActivityContentBased4: '-',
      bonusActivityContentBased5: '-',
      groupChallengeWinner1: 30,
      groupChallengeWinner2: 20,
      groupChallengeWinner3: 10,
      groupChallengeLeader: 10,
      preTopicSurvery: 5,
      postTopicSurvery: 5,
      updatedOn: '28 Feb 2022',
    },
  ],
};

const Overview = () => {
  const [serachValue, setSearchValue] = useState<string>();
  return (
    <>
      <div className='mb-5'>
        <InputText
          icon={<BiSearch />}
          type={'text'}
          value={serachValue}
          onChangeHandle={setSearchValue}
        />
      </div>
      <Table value={tableVal} />
    </>
  );
};

export default Overview;
